services:
  - type: web
    name: pochtovik-name-server
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: LOG_LEVEL
        value: info
